#!/bin/bash
# Push a version-bump PR to SlackBuildsOrg/slackbuilds, via the
# perrin4869/sbo fork, for a package that passed check.yml here.
#
# Deliberately re-derives from a FRESH upstream clone at HEAD rather than
# trusting this repo's copy or the SHA recorded in UPDATE.json - upstream may
# have rewritten the package (a mass script pass, another contributor's PR)
# since this repo's PR was reviewed, and upstream is always the source of
# truth. If the fresh result differs from what was reviewed, we still
# submit it (silently discarding stale reviewed output would be worse), but
# flag the drift loudly so a human notices.
#
# Usage:
#   scripts/submit.sh <prgnam> <version> <pkg_dir>
#
# <pkg_dir> is this repo's own <category>/<prgnam>/ - the same path the
# package occupies upstream, kept here as the diff baseline for future
# update PRs (see README's "Reviewing an update PR").
#
# Requires:
#   SBO_SUBMIT_TOKEN   - PAT with `repo` scope; GITHUB_TOKEN can't push to
#                         perrin4869/sbo or open PRs against SlackBuildsOrg.
#   SBO_FORK           - owner/repo of the fork to push branches to
#                         (default: perrin4869/sbo)
#   SBO_UPSTREAM       - owner/repo to open the PR against
#                         (default: SlackBuildsOrg/slackbuilds)

set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source scripts/lib.sh

prgnam="${1:?prgnam required}"
version="${2:?version required}"
pkg_dir="${3:?pkg dir required}"

: "${SBO_SUBMIT_TOKEN:?SBO_SUBMIT_TOKEN not set}"
SBO_FORK="${SBO_FORK:-perrin4869/sbo}"
SBO_UPSTREAM="${SBO_UPSTREAM:-${UPSTREAM_OWNER}/${UPSTREAM_REPO}}"

conf="packages/${prgnam}.conf"
[ -f "$conf" ] || die "no such package config: $conf"
load_package_conf "$conf"
[ "$prgnam" = "$PRGNAM" ] || die "packages/${prgnam}.conf declares PRGNAM=$PRGNAM"

[ -f "$pkg_dir/${PRGNAM}.info" ]       || die "missing $pkg_dir/${PRGNAM}.info"
[ -f "$pkg_dir/${PRGNAM}.SlackBuild" ] || die "missing $pkg_dir/${PRGNAM}.SlackBuild"

# --- re-check against upstream HEAD, not the SHA this PR was opened against -
current_upstream_version="$(upstream_version "$CATEGORY" "$PRGNAM")"
if [ -n "$current_upstream_version" ] && ! version_gt "$version" "$current_upstream_version"; then
    log "$PRGNAM: upstream already ships $current_upstream_version (>= $version) - skipping submit, someone else got there first"
    echo "SKIPPED $PRGNAM already-shipped $current_upstream_version"
    exit 0
fi

workdir="$(mktemp -d)"
trap 'rm -rf "$workdir"' EXIT

clone_url="https://x-access-token:${SBO_SUBMIT_TOKEN}@github.com/${SBO_UPSTREAM}.git"
log "cloning $SBO_UPSTREAM@${UPSTREAM_REF} fresh"
git clone --quiet --depth 1 --branch "$UPSTREAM_REF" "$clone_url" "$workdir/upstream"

fresh_dir="$workdir/fresh"
bash scripts/generate.sh "$prgnam" "$version" "$workdir/upstream" "$fresh_dir"

# --- drift check: fresh-derived output vs. what was reviewed in the PR -----
drifted=false
for f in "${PRGNAM}.info" "${PRGNAM}.SlackBuild"; do
    if ! diff -q "$fresh_dir/$f" "$pkg_dir/$f" >/dev/null 2>&1; then
        drifted=true
        log "warning: $f differs between the reviewed copy and a fresh regeneration - upstream moved since review. Using the fresh copy."
    fi
done

# --- push the branch + commit, using the fresh (not reviewed) files -------
upstream_pkg_dir="$workdir/upstream/${CATEGORY}/${PRGNAM}"
cp "$fresh_dir/${PRGNAM}.info" "$fresh_dir/${PRGNAM}.SlackBuild" "$upstream_pkg_dir/"

# pkg_dir is kept (not deleted) as the diff baseline for this package's
# *next* update PR - synced to the fresh copy, not the possibly-drifted
# reviewed one, so that baseline always reflects what was actually
# submitted. The caller (submit.yml) commits this only if it changed.
cp "$fresh_dir/${PRGNAM}.info" "$fresh_dir/${PRGNAM}.SlackBuild" "$pkg_dir/"

commit_msg="${CATEGORY}/${PRGNAM}: Updated for version ${version}"
branch="${PRGNAM}/${version}"

(
    cd "$workdir/upstream"
    git checkout --quiet -b "$branch"
    git add "${CATEGORY}/${PRGNAM}/${PRGNAM}.info" "${CATEGORY}/${PRGNAM}/${PRGNAM}.SlackBuild"
    git -c user.name="Julian Grinblat" -c user.email="julian@dotcore.co.il" \
        commit --quiet -m "$commit_msg"
    git remote add fork "https://x-access-token:${SBO_SUBMIT_TOKEN}@github.com/${SBO_FORK}.git"
    git push --quiet fork "HEAD:refs/heads/${branch}" --force-with-lease
)

fork_owner="${SBO_FORK%%/*}"
pr_body="Version bump generated by perrin4869/slackbuilds."
if [ "$drifted" = true ]; then
    pr_body="${pr_body}

**Note:** the .info/.SlackBuild reviewed in perrin4869/slackbuilds were regenerated against a fresh copy of ${SBO_UPSTREAM}@${UPSTREAM_REF} at submit time and differ slightly from what was originally reviewed - upstream likely moved in the meantime. Please double check."
fi

pr_url="$(GH_TOKEN="$SBO_SUBMIT_TOKEN" gh pr create \
    --repo "$SBO_UPSTREAM" \
    --base "$UPSTREAM_REF" \
    --head "${fork_owner}:${branch}" \
    --title "$commit_msg" \
    --body "$pr_body")"

log "opened $pr_url"
echo "SUBMITTED $PRGNAM $version $pr_url"
