CATEGORY=development
PRGNAM=jujutsu
SOURCE="https://github.com/jj-vcs/jj"
TAG_REGEX='^v([0-9]+\.[0-9]+\.[0-9]+)$'
STRATEGY=rust
IMAGE_VARIANT=rust-opt
SRC_URL="https://github.com/jj-vcs/jj/archive/refs/tags/v%VERSION%/jj-%VERSION%.tar.gz"
ARCHIVE="jj-%VERSION%.tar.gz"
PRGDIR="jj-%VERSION%"
