CATEGORY=libraries
PRGNAM=tree-sitter
SOURCE="https://github.com/tree-sitter/tree-sitter"
TAG_REGEX='^v([0-9]+\.[0-9]+\.[0-9]+)$'
SRC_URL="https://github.com/tree-sitter/tree-sitter/archive/v%VERSION%/tree-sitter-%VERSION%.tar.gz"
ARCHIVE="tree-sitter-%VERSION%.tar.gz"
PRGDIR="tree-sitter-%VERSION%"
