CATEGORY=system
PRGNAM=yq
SOURCE="https://github.com/mikefarah/yq"
TAG_REGEX='^v([0-9]+\.[0-9]+\.[0-9]+)$'
CHECK_IMAGE=google-go-lang
DOWNLOAD_URL="https://github.com/mikefarah/yq/archive/refs/tags/v%VERSION%/yq-%VERSION%.tar.gz"
