CATEGORY=system
PRGNAM=yq
SOURCE="https://github.com/mikefarah/yq"
TAG_REGEX='^v([0-9]+\.[0-9]+\.[0-9]+)$'
IMAGE_VARIANT=google-go-lang
SRC_URL="https://github.com/mikefarah/yq/archive/refs/tags/v%VERSION%/yq-%VERSION%.tar.gz"
ARCHIVE="yq-%VERSION%.tar.gz"
PRGDIR="yq-%VERSION%"
